dist: trusty
sudo: required
group: deprecated-2017Q2

# lib contains jar files to support running tests
cache:
  directories:
    - lib

# We only are going to test on jdk8 + jdk10.
# openjdk9 + oraclejdk10 were both removed from Ubuntu
 
# Mainly for jdk11
language: java
jdk:
  - openjdk11

addons:
  postgresql: 9.6

env:
  - TEST=junit
  - TEST=epinions
  - TEST=tatp
  - TEST=tpcc
  - TEST=voter
  - TEST=auctionmark
  - TEST=wikipedia
  - TEST=ycsb
  - TEST=seats
  - TEST=sibench
  - TEST=noop
  - TEST=smallbank
  - TEST=twitter
  - TEST=resourcestresser
  - TEST=chbenchmark

services:
  - mysql


before_install:
  - sudo mount -o remount,size=50% /var/ramfs

install:
  - echo $TRAVIS_JDK_VERSION
  - if [ $TRAVIS_JDK_VERSION == openjdk11 ]; then
      DB=mysql ;
    else
      DB=postgres ;
    fi
  - if [ $DB == mysql ]; then mysql -e "SELECT VERSION()";
      echo -e "[mysqld]\nlower_case_table_names=1" | sudo tee -a /etc/mysql/my.cnf ;
      sudo service mysql restart ;
      mysql -e "CREATE DATABASE IF NOT EXISTS ${TEST}" ;
      mysql -e "CREATE USER 'travis'@'localhost' IDENTIFIED BY 'travis'; GRANT ALL ON *.* TO 'travis'@'localhost'";
    elif [ $DB == postgres ]; then psql -c "SELECT VERSION()" -U travis;
      psql -c "create database $TEST" -U postgres ;
      psql -c "ALTER USER CURRENT_USER WITH PASSWORD 'travis'" -U travis;
    fi

before_script:
  - if [ $DB == mysql ]; then
      URLBASE=jdbc:mysql://localhost:3306 ;
      DRIVER=com.mysql.jdbc.Driver ;
      TYPE=mysql ;
    elif [ $DB == postgres ]; then
      URLBASE=jdbc:postgresql://localhost:5432 ;
      DRIVER=org.postgresql.Driver ;
      TYPE=postgres ;
    fi

script:
  - SCALEFACTOR=0.5
  - TIME=60
  - TERMINALS=3
  - if [ $TEST == chbenchmark ]; then
      BENCH=${TEST},tpcc ;
    else
      BENCH=${TEST} ;
    fi
  - ./mvnw clean package
    config=config/${DB}/sample_${TEST}_config.xml ;
    sed -i
        -e "/<type>/c\<type>${TYPE}</type>"
        -e "/<driver>/c\<driver>${DRIVER}</driver>"
        -e "/<url>/c\<url>${URLBASE}/${TEST}</url>"
        -e "/<username>/c\<username>travis</username>"
        -e "/<password>/c\<password>travis</password>"
        -e "/<scalefactor>/c\\<scalefactor>${SCALEFACTOR}</scalefactor>"
        -e "/<terminals>/c\<terminals>${TERMINALS}</terminals>"
        -e "/<time>/c\<time>${TIME}</time>"
        -e "/<isolation>/c\<isolation>TRANSACTION_READ_COMMITTED</isolation>"
        "${config}";
      cd target
      unzip oltpbench2-20.1.3-SNAPSHOT.zip
      cd oltpbench2-20.1.3-SNAPSHOT
      java -jar oltpbench2.jar -b "${BENCH}" -c "${config}" --create=true --load=true --execute=true -s 5
    fi

after_script:
  - if [ $DB == mysql ]; then
      mysql -e "DROP DATABASE IF EXISTS ${TEST}" ;
    elif [ $DB == postgres ]; then
      psql -c "DROP DATABASE IF EXISTS ${TEST}" -U postgres ;
    fi
