dist: trusty
sudo: required
group: deprecated-2017Q2

# lib contains jar files to support running tests
cache:
  directories:
    - lib

# We only are going to test on jdk8 + jdk10.
# openjdk9 + oraclejdk10 were both removed from Ubuntu
 
# Mainly for jdk11
language: java
jdk:
  - openjdk10
  - openjdk8
  - oraclejdk8

