dist: trusty
sudo: required
group: deprecated-2017Q2

# lib contains jar files to support running tests
cache:
  directories:
    - lib

# We only are going to test on jdk8 + jdk10.
# openjdk9 + oraclejdk10 were both removed from Ubuntu
 
# Mainly for jdk11
language: java
jdk:
  - openjdk11

addons:
  postgresql: 9.6

env:
  - TEST=junit
  - TEST=epinions
  - TEST=tatp
  - TEST=tpcc
  - TEST=voter
  - TEST=auctionmark
  - TEST=wikipedia
  - TEST=ycsb
  - TEST=seats
  - TEST=sibench
  - TEST=noop
  - TEST=smallbank
  - TEST=twitter
  - TEST=resourcestresser
  - TEST=chbenchmark

services:
  - mysql


before_install:
  - sudo mount -o remount,size=50% /var/ramfs

install:
  - echo $TRAVIS_JDK_VERSION
  - if [ $TRAVIS_JDK_VERSION == openjdk11 ]; then
      DB=mysql ;
    else
      DB=postgres ;
    fi
  - if [ $DB == mysql ]; then mysql -e "SELECT VERSION()";
      echo -e "[mysqld]\nlower_case_table_names=1" | sudo tee -a /etc/mysql/my.cnf ;
      sudo service mysql restart ;
      mysql -e "CREATE DATABASE IF NOT EXISTS ${TEST}" ;
      mysql -e "CREATE USER 'travis'@'localhost' IDENTIFIED BY 'travis'; GRANT ALL ON *.* TO 'travis'@'localhost'";
    elif [ $DB == postgres ]; then psql -c "SELECT VERSION()" -U travis;
      psql -c "create database $TEST" -U postgres ;
      psql -c "ALTER USER CURRENT_USER WITH PASSWORD 'travis'" -U travis;
    fi


